version: 2.1

workflows:
  main:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/go:1.17.7
    steps:
      - checkout
      - run:
          name: "Download Dependancies"
          command: |
            go mod download
            sudo apt-get update && sudo apt-get install -y libappindicator3-dev libgtk-3-dev
      - run:
          name: "Run Tests"
          command: |
            ./build.sh -v ./...
