version: 2.1

orbs:
  go: circleci/go@1.7

workflows:
  main:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/go:1.17.7
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - run:
          name: "Download Dependancies"
          command: |
            sudo apt-get update && sudo apt-get install -y libappindicator3-dev libgtk-3-dev
      - run:
          name: "Run Tests"
          command: |
            ./build.sh -v ./...
      - go/save-cache
