version: 2.1

orbs:
  go: circleci/go@1.7
  gor: hubci/goreleaser@1.0

workflows:
  main:
    jobs:
      - test
  release:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              # Simplified SemVer regex
              only: /^v\d+\.\d+\.\d+$/
      - gor/release:
          version: "1.10.2"
          go-version: "1.18.4"
          filters:
            branches:
              ignore: /.*/
            tags:
              # Simplified SemVer regex
              only: /^v\d+\.\d+\.\d+$/
          context: main

jobs:
  test:
    docker:
      - image: cimg/go:1.18.4
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - run:
          name: "Download Dependancies"
          command: |
            sudo apt-get update && sudo apt-get install -y libappindicator3-dev libgtk-3-dev
      - run:
          name: "Run Tests"
          command: |
            ./build.sh -v ./...
      - go/save-cache
